//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _3_Capas.WSCamiones {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WSCamiones.serviceSoap")]
    public interface serviceSoap {
        
        // CODEGEN: Generating message contract since element name Calle from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsOriginDestino", ReplyAction="*")]
        _3_Capas.WSCamiones.InsOriginDestinoResponse InsOriginDestino(_3_Capas.WSCamiones.InsOriginDestinoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsOriginDestino", ReplyAction="*")]
        System.Threading.Tasks.Task<_3_Capas.WSCamiones.InsOriginDestinoResponse> InsOriginDestinoAsync(_3_Capas.WSCamiones.InsOriginDestinoRequest request);
        
        // CODEGEN: Generating message contract since element name Descripcion from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsCargamento", ReplyAction="*")]
        _3_Capas.WSCamiones.InsCargamentoResponse InsCargamento(_3_Capas.WSCamiones.InsCargamentoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsCargamento", ReplyAction="*")]
        System.Threading.Tasks.Task<_3_Capas.WSCamiones.InsCargamentoResponse> InsCargamentoAsync(_3_Capas.WSCamiones.InsCargamentoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsOriginDestinoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsOriginDestino", Namespace="http://tempuri.org/", Order=0)]
        public _3_Capas.WSCamiones.InsOriginDestinoRequestBody Body;
        
        public InsOriginDestinoRequest() {
        }
        
        public InsOriginDestinoRequest(_3_Capas.WSCamiones.InsOriginDestinoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsOriginDestinoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Calle;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Numero;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Colonia;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Ciudad;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Estado;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string CP;
        
        public InsOriginDestinoRequestBody() {
        }
        
        public InsOriginDestinoRequestBody(string Calle, string Numero, string Colonia, string Ciudad, string Estado, string CP) {
            this.Calle = Calle;
            this.Numero = Numero;
            this.Colonia = Colonia;
            this.Ciudad = Ciudad;
            this.Estado = Estado;
            this.CP = CP;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsOriginDestinoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsOriginDestinoResponse", Namespace="http://tempuri.org/", Order=0)]
        public _3_Capas.WSCamiones.InsOriginDestinoResponseBody Body;
        
        public InsOriginDestinoResponse() {
        }
        
        public InsOriginDestinoResponse(_3_Capas.WSCamiones.InsOriginDestinoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsOriginDestinoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int InsOriginDestinoResult;
        
        public InsOriginDestinoResponseBody() {
        }
        
        public InsOriginDestinoResponseBody(int InsOriginDestinoResult) {
            this.InsOriginDestinoResult = InsOriginDestinoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsCargamentoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsCargamento", Namespace="http://tempuri.org/", Order=0)]
        public _3_Capas.WSCamiones.InsCargamentoRequestBody Body;
        
        public InsCargamentoRequest() {
        }
        
        public InsCargamentoRequest(_3_Capas.WSCamiones.InsCargamentoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsCargamentoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long IdRuta;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Descripcion;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public double Peso;
        
        public InsCargamentoRequestBody() {
        }
        
        public InsCargamentoRequestBody(long IdRuta, string Descripcion, double Peso) {
            this.IdRuta = IdRuta;
            this.Descripcion = Descripcion;
            this.Peso = Peso;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsCargamentoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsCargamentoResponse", Namespace="http://tempuri.org/", Order=0)]
        public _3_Capas.WSCamiones.InsCargamentoResponseBody Body;
        
        public InsCargamentoResponse() {
        }
        
        public InsCargamentoResponse(_3_Capas.WSCamiones.InsCargamentoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsCargamentoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string InsCargamentoResult;
        
        public InsCargamentoResponseBody() {
        }
        
        public InsCargamentoResponseBody(string InsCargamentoResult) {
            this.InsCargamentoResult = InsCargamentoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface serviceSoapChannel : _3_Capas.WSCamiones.serviceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class serviceSoapClient : System.ServiceModel.ClientBase<_3_Capas.WSCamiones.serviceSoap>, _3_Capas.WSCamiones.serviceSoap {
        
        public serviceSoapClient() {
        }
        
        public serviceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public serviceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public serviceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public serviceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        _3_Capas.WSCamiones.InsOriginDestinoResponse _3_Capas.WSCamiones.serviceSoap.InsOriginDestino(_3_Capas.WSCamiones.InsOriginDestinoRequest request) {
            return base.Channel.InsOriginDestino(request);
        }
        
        public int InsOriginDestino(string Calle, string Numero, string Colonia, string Ciudad, string Estado, string CP) {
            _3_Capas.WSCamiones.InsOriginDestinoRequest inValue = new _3_Capas.WSCamiones.InsOriginDestinoRequest();
            inValue.Body = new _3_Capas.WSCamiones.InsOriginDestinoRequestBody();
            inValue.Body.Calle = Calle;
            inValue.Body.Numero = Numero;
            inValue.Body.Colonia = Colonia;
            inValue.Body.Ciudad = Ciudad;
            inValue.Body.Estado = Estado;
            inValue.Body.CP = CP;
            _3_Capas.WSCamiones.InsOriginDestinoResponse retVal = ((_3_Capas.WSCamiones.serviceSoap)(this)).InsOriginDestino(inValue);
            return retVal.Body.InsOriginDestinoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<_3_Capas.WSCamiones.InsOriginDestinoResponse> _3_Capas.WSCamiones.serviceSoap.InsOriginDestinoAsync(_3_Capas.WSCamiones.InsOriginDestinoRequest request) {
            return base.Channel.InsOriginDestinoAsync(request);
        }
        
        public System.Threading.Tasks.Task<_3_Capas.WSCamiones.InsOriginDestinoResponse> InsOriginDestinoAsync(string Calle, string Numero, string Colonia, string Ciudad, string Estado, string CP) {
            _3_Capas.WSCamiones.InsOriginDestinoRequest inValue = new _3_Capas.WSCamiones.InsOriginDestinoRequest();
            inValue.Body = new _3_Capas.WSCamiones.InsOriginDestinoRequestBody();
            inValue.Body.Calle = Calle;
            inValue.Body.Numero = Numero;
            inValue.Body.Colonia = Colonia;
            inValue.Body.Ciudad = Ciudad;
            inValue.Body.Estado = Estado;
            inValue.Body.CP = CP;
            return ((_3_Capas.WSCamiones.serviceSoap)(this)).InsOriginDestinoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        _3_Capas.WSCamiones.InsCargamentoResponse _3_Capas.WSCamiones.serviceSoap.InsCargamento(_3_Capas.WSCamiones.InsCargamentoRequest request) {
            return base.Channel.InsCargamento(request);
        }
        
        public string InsCargamento(long IdRuta, string Descripcion, double Peso) {
            _3_Capas.WSCamiones.InsCargamentoRequest inValue = new _3_Capas.WSCamiones.InsCargamentoRequest();
            inValue.Body = new _3_Capas.WSCamiones.InsCargamentoRequestBody();
            inValue.Body.IdRuta = IdRuta;
            inValue.Body.Descripcion = Descripcion;
            inValue.Body.Peso = Peso;
            _3_Capas.WSCamiones.InsCargamentoResponse retVal = ((_3_Capas.WSCamiones.serviceSoap)(this)).InsCargamento(inValue);
            return retVal.Body.InsCargamentoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<_3_Capas.WSCamiones.InsCargamentoResponse> _3_Capas.WSCamiones.serviceSoap.InsCargamentoAsync(_3_Capas.WSCamiones.InsCargamentoRequest request) {
            return base.Channel.InsCargamentoAsync(request);
        }
        
        public System.Threading.Tasks.Task<_3_Capas.WSCamiones.InsCargamentoResponse> InsCargamentoAsync(long IdRuta, string Descripcion, double Peso) {
            _3_Capas.WSCamiones.InsCargamentoRequest inValue = new _3_Capas.WSCamiones.InsCargamentoRequest();
            inValue.Body = new _3_Capas.WSCamiones.InsCargamentoRequestBody();
            inValue.Body.IdRuta = IdRuta;
            inValue.Body.Descripcion = Descripcion;
            inValue.Body.Peso = Peso;
            return ((_3_Capas.WSCamiones.serviceSoap)(this)).InsCargamentoAsync(inValue);
        }
    }
}
